# Generated by Django 5.2.1 on 2025-05-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_lens', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
