# Generated by Django 5.2.1 on 2025-05-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_lens', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Страна'),
        ),
    ]
