# Generated by Django 5.2.1 on 2025-05-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_lens', '0005_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='phone_country',
        ),
    ]
